name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t your-dockerhub-username/kaggle-image .

      - name: Push Docker image to DockerHub
        run: docker push your-dockerhub-username/kaggle-image
