name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    steps:
      - name: Free up disk space
        run: |
          apt-get clean
          rm -rf /usr/local/lib/android
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc

      - name: Install Dockerhub
        run: |
          apt-get update -y && apt-get upgrade -y
          apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t your-dockerhub-username/kaggle-image .

      - name: Push Docker image to DockerHub
        run: docker push your-dockerhub-username/kaggle-image
